### ISSUE TITLE
Multi-line secrets don't work

### ISSUE THREAD

**Issue by ikke-t** [hybrid-cloud-patterns/multicloud-gitops#62]
I tried to push secret to vault, and run into problem secrets are read line by line, not as yaml key: value.

Example:
```yaml
secrets:
  ldap:
    bindPassword: xxx
    bindDN: xxx
    url: xxx
    groupsBaseDN: xxx
    usersBaseDN: xxx
    ca_crt: |
      -----BEGIN CERTIFICATE-----
      MIIEgjCCAuqgAwIBAgIBATANBgkqhkiG9w0BAQsFADAzMREwDwYDVQQKDAhDT09M
      LkxBQjEeMBwGA1UEAwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTIyMDEwNTEz
      ...
```

Error:

```yaml
"rc": 127, "return_code": 127, "stderr": "Failed to parse K=V data: invalid key/value pair \"CERTIFICATE-----\": format must be key=value\nsh: line 1: MIIEgjCCAuqgAwIBAgIBATANBgkqhkiG9w0BAQsFADAzMREwDwYDVQQKDAhDT09M: command not found\nsh: line 2: LkxBQjEeMBwGA1UEAwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTIyMDEwNTEz: command not found\nsh: line 3: MjA1MloXDTQyMDEwNTEzMjA1MlowMzERMA8GA1UECgwIQ09PTC5MQUIxHjAcBgNV: command not found\nsh: line 4: BAMMFUNlcnRpZmljYXRlIEF1dGhvcml0eTCCAaIwDQYJKoZIhvcNAQEBBQADggGP: command not found\nsh: line 5: ADCCAYoCggGBANhvBhWj5qQWpvO6h6yDvCKhc/Nj36xZN1990L2PGL6dJU2SoOuo: No such file or directory\n
```

**Comment by ikke-t** [comment]
this did get rid of the error lines. didn't check the actual vault content after running it: https://github.com/hybrid-cloud-patterns/common/pull/81/files

**Comment by mbaldessari** [comment]
For now I merged the PR in common and updated multicloud-gitops as well. Let's close this only once we're 100% sure that the whole cert in vault via multilines is addressed.

**Comment by ikke-t** [comment]
it's actually still broken. Now I had time to take this further, and I noticed the secret is messed up. This is what I have in values-secrets:

```
secrets:
  ldap:
    bindPassword: foooooooo
    bindDN: "uid=aap_ldap,cn=sysaccounts,cn=etc,dc=cool,dc=lab"
    url: "ldaps://rh-idm-01.cool.lab"
    groupsBaseDN: "cn=groups,cn=accounts,dc=cool,dc=lab"
    usersBaseDN: "cn=users,cn=accounts,dc=cool,dc=lab"
    ca_crt: |
      -----BEGIN CERTIFICATE-----
      MIIEgjCCAuqgAwIBAgIBATANBgkqhkiG9w0BAQsFADAzMREwDwYDVQQKDAhDT09M
      LkxBQjEeMBwGA1UEAwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTIyMDEwNTEz
...
      -----END CERTIFICATE-----
```

And this is what the vault looks like, so it has created one ldap secret called bindPassword, which has the rest of the yaml as value:

```
foooooooo bindDN=uid=aap_ldap,cn=sysaccounts,cn=etc,dc=cool,dc=lab url=ldaps://rh-idm-01.cool.lab groupsBaseDN=cn=groups,cn=accounts,dc=cool,dc=lab usersBaseDN=cn=users,cn=accounts,dc=cool,dc=lab ca_crt=-----BEGIN CERTIFICATE-----
MIIEgjCCAuqgAwIBAgIBATANBgkqhkiG9w0BAQsFADAzMREwDwYDVQQKDAhDT09M
LkxBQjEeMBwGA1UEAwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTIyMDEwNTEz
...
-----END CERTIFICATE-----

**Comment by mbaldessari** [comment]
@ikke-t Can you check if https://github.com/hybrid-cloud-patterns/common/pull/82 ? I have put all the rationale + testing in the commit message, I think this should fix this?

**Comment by mbaldessari** [comment]
If you still have issues on this, please do reopen this issue. It got closed automatically by the last PR
